### ISSUE TITLE
Values in config file

### ISSUE THREAD

**Issue by farhad-dalirani** [hku-mars/r3live#149]
Can you please explain these values in the config file?

```
Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6
   using_raw_point: 1
   point_step: 1
   
```

Thank you,
